spring.application.name=restaurant
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/los_patos
spring.datasource.username=postgres
spring.datasource.password=76858382
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS & REST Configurations
spring.mvc.servlet.path=/


# CONFIGURACIÓN DE CORREO REAL (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rgiancarloc_ac@hotmail.com
spring.mail.password=casuro78
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# INTEGRACIÓN CON WEBHOOK DE n8n (PARA NOTIFICACIONES EN TELEGRAM)
app.webhook.n8n=https://rcginca.app.n8n.cloud/webhook-test/nuevo-pedido